steps:
  - label: "🔧 Setup Environment"
    commands:
      - git lfs install
      - git lfs pull
      - echo "Environment setup completed"

  - label: "🚀 Build Project"
    command: make build || npm run build || echo "Build step"

  - label: "✅ Test"
    command: make test || npm test || echo "Test step"
