[build-system]
requires = ["setuptools>=65.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vortex-ai"
version = "1.0.0"
dependencies = [
    "flask>=3.0.0",
    "psutil>=5.9.5",
    "requests>=2.31.0",
]
