steps:
  - label: "📥 Checkout with LFS"
    commands:
      - git lfs install
      - git lfs fetch
      - git lfs checkout
      - git lfs ls-files

  - label: "🛠️ Build"
    command: |
      echo "Building project..."
      # دستورات build شما
      ls -la

  - label: "🧪 Test"
    command: |
      echo "Running tests..."
      # دستورات test شما

  - wait

  - label: "🚀 Deploy"
    command: echo "Deploying..."
    if: build.branch == "main"
