# 📁 config/production.yaml

environment: "production"
debug: false

logging:
  level: "INFO"
  file: "logs/production.log"
  max_size: "100MB"
  backup_count: 10

api:
  host: "0.0.0.0"
  port: 8000
  cors_origins: ["https://yourapp.com"]
  rate_limiting:
    requests_per_minute: 1000
    burst_limit: 100

database:
  url: "postgresql://user:pass@localhost/crypto_analyzer"
  pool_size: 20
  max_overflow: 30

cache:
  type: "redis"
  url: "redis://localhost:6379"
  ttl: 600

data_sources:
  primary: "api"
  fallback: "github"
  rate_limiting:
    requests_per_minute: 60
    burst_limit: 10

security:
  api_key_required: true
  ssl_required: true
  cors_enabled: true

monitoring:
  health_check_interval: 30
  metrics_enabled: true
  alerting_enabled: true
